# Generated by Django 3.1.5 on 2021-03-20 05:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('staffId', models.IntegerField(primary_key=True, serialize=False)),
                ('selected_duties', django_mysql.models.ListTextField(models.IntegerField(), size=50)),
                ('selected_staff', django_mysql.models.ListTextField(models.IntegerField(), size=50)),
            ],
        ),
    ]
