# Generated by Django 3.1.5 on 2021-03-20 06:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('rostaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='selected_duties',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, size=50),
        ),
        migrations.AlterField(
            model_name='config',
            name='selected_staff',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, size=50),
        ),
    ]
