# Generated by Django 3.1.5 on 2021-03-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostaApp', '0002_auto_20210320_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='selected_duties',
        ),
        migrations.RemoveField(
            model_name='config',
            name='selected_staff',
        ),
    ]
