# Generated by Django 3.1.5 on 2021-03-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostaApp', '0004_auto_20210320_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='staffId',
            new_name='userId',
        ),
    ]
