# Generated by Django 3.1.5 on 2021-01-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('dutyId', models.AutoField(primary_key=True, serialize=False)),
                ('dutyType', models.CharField(max_length=20)),
                ('dutyCode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=15)),
                ('userName', models.CharField(max_length=26)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alloc',
            fields=[
                ('allocId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isAM', models.BooleanField()),
                ('duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.duty')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
            ],
        ),
    ]
