# Generated by Django 3.1.5 on 2021-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210108_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='dutyType',
            field=models.CharField(max_length=50),
        ),
    ]
