# Generated by Django 3.1.5 on 2021-01-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210108_1034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alloc',
            unique_together={('date', 'session', 'staff')},
        ),
    ]
