# Generated by Django 3.1.5 on 2021-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210322_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='sortIndex',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SuperUser', 'Super User'), ('StdUser', 'Standard User'), ('Guest', 'Guest')], default='Guest', max_length=20),
        ),
    ]
