# Generated by Django 3.1.5 on 2021-04-25 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20210402_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocLog',
            fields=[
                ('allocLogId', models.AutoField(primary_key=True, serialize=False)),
                ('allocId', models.IntegerField()),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=2)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.duty')),
                ('savedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
            ],
            options={
                'unique_together': {('date', 'session', 'staff')},
            },
        ),
    ]
