# Generated by Django 3.1.5 on 2021-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alloclog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alloclog',
            unique_together=set(),
        ),
    ]
