# Generated by Django 3.1.5 on 2021-05-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210425_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.staff'),
        ),
    ]
