# Generated by Django 3.1.5 on 2021-05-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
