# Generated by Django 3.1.5 on 2021-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMessages', '0002_auto_20210123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='datePosted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
