# Generated by Django 3.1.5 on 2021-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMessages', '0003_auto_20210123_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='datePosted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
